- core-examples/src/main/java/io/vertx/example/core/eventbus/pubsub/Sender.java
- rx-examples/README.adoc
- rx-examples/src/main/java/io/vertx/example/rxjava/eventbus/pingpong/PingPong.java
Add example of rx send and reply.
Fix sender example to use rx.
Signed-off-by: John Oliver <johno@insightfullogic.com>
> Add example of rx send and reply.

- apex-examples/README.adoc
- apex-examples/src/main/java/io/vertx/example/apex/realtime/Chat.java
- apex-examples/src/main/java/io/vertx/example/apex/realtime/webroot/chat.html
- apex-examples/src/main/java/io/vertx/example/util/Runner.java
Also, associated HTML/JS content.
> Added realtime chat verticle example

- core-examples/src/main/groovy/io/vertx/example/core/http/sharing/client.groovy
- core-examples/src/main/java/io/vertx/example/core/http/sharing/Client.java
- core-examples/src/main/java/io/vertx/example/core/http/sharing/Server.java
- core-examples/src/main/js/io/vertx/example/core/http/sharing/client.js
- core-examples/src/main/rb/io/vertx/example/core/http/sharing/client.rb
Just an example illustrating the HTTP server sharing:
* The server has two verticles serving on the same port
* The client periodically requests the server and print the result
> Add an example illustrating the HTTP Server sharing

- docker-examples/README.adoc
- docker-examples/vertx-docker-example-fabric8/README.md
- docker-examples/vertx-docker-example-fabric8/pom.xml
- docker-examples/vertx-docker-example-fabric8/src/main/docker/assembly.xml
- docker-examples/vertx-docker-example-fabric8/src/main/java/io/vertx/example/HelloWorldVerticle.java
- docker-examples/vertx-docker-example/README.md
- docker-examples/vertx-docker-example/pom.xml
- docker-examples/vertx-docker-example/src/main/docker/Dockerfile
- docker-examples/vertx-docker-example/src/main/java/io/vertx/example/HelloWorldVerticle.java
- docker-examples/vertx-docker-groovy/Dockerfile
- docker-examples/vertx-docker-groovy/hello-verticle.groovy
- docker-examples/vertx-docker-java-fatjar/Dockerfile
- docker-examples/vertx-docker-java-fatjar/pom.xml
- docker-examples/vertx-docker-java-fatjar/src/main/java/io/vertx/sample/hello/HelloVerticle.java
- docker-examples/vertx-docker-java/Dockerfile
- docker-examples/vertx-docker-java/pom.xml
- docker-examples/vertx-docker-java/src/main/java/io/vertx/sample/hello/HelloVerticle.java
- docker-examples/vertx-docker-javascript/Dockerfile
- docker-examples/vertx-docker-javascript/hello-verticle.js
- docker-examples/vertx-docker-ruby/Dockerfile
- docker-examples/vertx-docker-ruby/hello-verticle.rb
- maven-verticle/src/main/java/io/vertx/example/HelloWorldVerticle.java
- pom.xml
Just a move of the docker examples.
Signed-off-by: Clement Escoffier <clement.escoffier@gmail.com>
> Move the docker examples from the vert-stack to the vert-examples

- web-examples/README.adoc
- web-examples/src/main/java/io/vertx/example/web/form/Server.java
> form example

- core-examples/README.adoc
- core-examples/src/main/groovy/io/vertx/example/core/verticle/worker/mainverticle.groovy
- core-examples/src/main/groovy/io/vertx/example/core/verticle/worker/workerverticle.groovy
- core-examples/src/main/java/io/vertx/example/core/verticle/worker/MainVerticle.java
- core-examples/src/main/java/io/vertx/example/core/verticle/worker/WorkerVerticle.java
- core-examples/src/main/js/io/vertx/example/core/verticle/worker/mainverticle.js
- core-examples/src/main/js/io/vertx/example/core/verticle/worker/workerverticle.js
- core-examples/src/main/rb/io/vertx/example/core/verticle/worker/mainverticle.rb
- core-examples/src/main/rb/io/vertx/example/core/verticle/worker/workerverticle.rb
A very simple example of a worker verticle and how to interact with it using the event bus. The example prints the current thread name to depict the thread switches.
> Add an example using a worker verticle

- README.adoc
> Typo in README.adoc

- examples-utils/src/main/java/io/vertx/example/util/ExampleRunner.java
- web-examples/README.adoc
- web-examples/src/main/java/io/vertx/example/util/Runner.java
- web-examples/src/main/java/io/vertx/example/web/staticsite/Server.java
- web-examples/src/main/java/io/vertx/example/web/staticsite/webroot/index.html
- web-examples/src/main/java/io/vertx/example/web/staticsite/webroot/page1.html
- web-examples/src/main/java/io/vertx/example/web/staticsite/webroot/page2.html
@vietj @cescoffier @pmlopes please review
> Added simple static web server example that does redeploy

- core-examples/README.adoc
- core-examples/src/main/groovy/io/vertx/example/core/ha/server.groovy
- core-examples/src/main/java/io/vertx/example/core/ha/Server.java
- core-examples/src/main/js/io/vertx/example/core/ha/server.js
- core-examples/src/main/rb/io/vertx/example/core/ha/server.rb
Just an example to illustrate the HA behavior.
@vietj / @purplefox please review.
> Add an example illustrating HA behavior

- README.adoc
- springboot-example/README.adoc
- springboot-example/pom.xml
- springboot-example/src/main/java/io/vertx/example/Application.java
- springboot-example/src/main/resources/webroot/index.html
- springboot-example/src/main/resources/webroot/page1.html
- springboot-example/src/main/resources/webroot/page2.html
@cescoffier @pmlopes @vietj please review
> Springboot example

- README.adoc
- jdbc-examples/README.adoc
- jdbc-examples/pom.xml
- jdbc-examples/src/main/groovy/io/vertx/example/jdbc/query_params/jdbc_example.groovy
- jdbc-examples/src/main/groovy/io/vertx/example/jdbc/simple/jdbc_example.groovy
- jdbc-examples/src/main/groovy/io/vertx/example/jdbc/transaction/jdbc_example.groovy
- jdbc-examples/src/main/groovy/io/vertx/example/jdbc/transaction_rollback/jdbc_example.groovy
- jdbc-examples/src/main/java/io/vertx/example/jdbc/query_params/JDBCExample.java
- jdbc-examples/src/main/java/io/vertx/example/jdbc/simple/JDBCExample.java
- jdbc-examples/src/main/java/io/vertx/example/jdbc/transaction/JDBCExample.java
- jdbc-examples/src/main/java/io/vertx/example/jdbc/transaction_rollback/JDBCExample.java
- jdbc-examples/src/main/java/io/vertx/example/util/Runner.java
- jdbc-examples/src/main/js/io/vertx/example/jdbc/query_params/jdbc_example.js
- jdbc-examples/src/main/js/io/vertx/example/jdbc/simple/jdbc_example.js
- jdbc-examples/src/main/js/io/vertx/example/jdbc/transaction/jdbc_example.js
- jdbc-examples/src/main/js/io/vertx/example/jdbc/transaction_rollback/jdbc_example.js
- jdbc-examples/src/main/rb/io/vertx/example/jdbc/query_params/jdbc_example.rb
- jdbc-examples/src/main/rb/io/vertx/example/jdbc/simple/jdbc_example.rb
- jdbc-examples/src/main/rb/io/vertx/example/jdbc/transaction/jdbc_example.rb
- jdbc-examples/src/main/rb/io/vertx/example/jdbc/transaction_rollback/jdbc_example.rb
- pom.xml
Signed-off-by: Paulo Lopes <paulo@mlopes.net>
* basic ops
* query with params
* trasactions
* rollback
> Simple set of JDBC examples

- README.adoc
- pom.xml
- spring-example/README.adoc
- spring-example/pom.xml
- spring-example/src/main/java/io/vertx/examples/spring/SpringExampleRunner.java
- spring-example/src/main/java/io/vertx/examples/spring/context/ExampleSpringConfiguration.java
- spring-example/src/main/java/io/vertx/examples/spring/entity/Product.java
- spring-example/src/main/java/io/vertx/examples/spring/repository/ProductRepository.java
- spring-example/src/main/java/io/vertx/examples/spring/service/ProductService.java
- spring-example/src/main/java/io/vertx/examples/spring/verticle/ServerVerticle.java
- spring-example/src/main/java/io/vertx/examples/spring/verticle/SpringDemoVerticle.java
- spring-example/src/main/resources/application.properties
- spring-example/src/main/resources/products.sql
Added a simple spring vertx example showing how to use vertx to wrap services wired up by a
Spring application context. 
We can extend this once people who are interested in vertx + spring offer some feedback to see if
we can identify patterns for their use-cases (if not covered by this trivial example)
> Initial version of spring-vertx example - see README.adoc for details

- web-examples/README.adoc
I just fixed a broken link in web-examples/README.adoc
> Fixed broken link

- web-examples/src/main/java/io/vertx/example/web/angularjs/Server.java
- web-examples/src/main/java/io/vertx/example/web/angularjs/webroot/js/app.js
- web-examples/src/main/java/io/vertx/example/web/angularjs/webroot/tpl/edit.html
- web-examples/src/main/java/io/vertx/example/web/angularjs/webroot/tpl/lists.html
Hello,
The display list was correct but no way to edit (update or delete) the users.
I tested it with two differents mongo release from docker hub (2.6 and 3.0.x)
I hope to help about two differents points :
- The first one is changing id by _id in all pages html, js and Java. 
- The second is about the delete method in app.js 
For the first point, I am not sure because I am a newbie with mongo so maybe it is not a good idea to use directly _id. It seems the mongo example use it netherless.
Another dirty solution is to add an id during loading users.
For the second point, it is a syntax problem with angular. Nothing else.
Thank you very much for all examples. They are awesome.
If it is good for you, i can update the other langages.
Best regards,
Nicolas
> FIX: id management

- gradle-simplest/build.gradle
Little update in the gradle build file
> Update build.gradle to vert.x 3.0.0 final

- README.adoc
- mongo-examples/README.adoc
- pom.xml
I've noticed some examples using mongodb, but none of them were primarily concerned about it, so i wrote the example.
The structure of the project is based on the vertx-redis example.
I hope you'll like it.
Vitor Freitas
> Mongo example

- maven-simplest/README.adoc
- maven-simplest/pom.xml
rename the main class property to conform to exec:java
> allow for mvn exec:java

- heroku-example/Procfile
- heroku-example/README.md
- heroku-example/pom.xml
- heroku-example/src/main/java/io/vertx/example/HelloWorldVerticle.java
- pom.xml
@jkutner as we spoke at devoxx, we can quickly deploy vert.x to heroku since we have fat jars. This would be an starter example, could you give a quick look and see if this is all correct?
> Basic Heroku support

- README.adoc
> Gradle verticle broken link

- spring-examples/springboot-example/src/main/java/io/vertx/example/Application.java
- spring-examples/springboot-example/src/main/java/io/vertx/example/StaticServer.java
Updated Spring Boot example to run server via Verticle
> Updated Spring Boot example to run server via Verticle

- .gitignore
- web-examples/README.adoc
- web-examples/src/main/java/io/vertx/example/web/react/.babelrc
- web-examples/src/main/java/io/vertx/example/web/react/.eslintrc
- web-examples/src/main/java/io/vertx/example/web/react/Server.java
- web-examples/src/main/java/io/vertx/example/web/react/app-client.js
- web-examples/src/main/java/io/vertx/example/web/react/package.json
- web-examples/src/main/java/io/vertx/example/web/react/webpack.config.js
- web-examples/src/main/java/io/vertx/example/web/react/webroot/index.html
This a simple real time chat application built on react
Fixes #128
> Add a better react example

- mail-examples/src/main/groovy/io/vertx/example/mail/mail_images.groovy
- mail-examples/src/main/java/io/vertx/example/mail/MailImages.java
- mail-examples/src/main/js/io/vertx/example/mail/mail_images.js
- mail-examples/src/main/rb/io/vertx/example/mail/mail_images.rb
this pr depends on vert-x3/vertx-mail-client#66
> add inline images example

- metrics-examples/src/main/groovy/io/vertx/example/metrics/dashboard/webroot/vertx-eventbus.js
- metrics-examples/src/main/js/io/vertx/example/metrics/dashboard/webroot/vertx-eventbus.js
- metrics-examples/src/main/rb/io/vertx/example/metrics/dashboard/webroot/vertx-eventbus.js
- service-proxy-examples/service-provider/src/main/java/io/vertx/examples/service/webroot/vertx-eventbus.js
- web-examples/src/main/groovy/io/vertx/example/web/chat/webroot/vertx-eventbus.js
- web-examples/src/main/java/io/vertx/example/web/chat/webroot/vertx-eventbus.js
- web-examples/src/main/java/io/vertx/example/web/realtime/webroot/vertx-eventbus.js
- web-examples/src/main/js/io/vertx/example/web/chat/webroot/vertx-eventbus.js
vertx-eventbus.js to version 3.3.2
> update vertx-eventbus.js version 3.3.2 

- pom.xml
- resteasy-examples/README.adoc
- resteasy-examples/pom.xml
- resteasy-examples/src/main/java/io/vertx/examples/resteasy/asyncresponse/Controller.java
- resteasy-examples/src/main/java/io/vertx/examples/resteasy/asyncresponse/Main.java
- resteasy-examples/src/main/java/io/vertx/examples/resteasy/asyncresponse/ProductBackend.java
- resteasy-examples/src/main/java/io/vertx/examples/resteasy/asyncresponse/Server.java
- resteasy-examples/src/main/java/io/vertx/examples/resteasy/helloworld/HelloWorldService.java
- resteasy-examples/src/main/java/io/vertx/examples/resteasy/helloworld/Server.java
- resteasy-examples/src/main/java/io/vertx/examples/resteasy/util/Runner.java
@cescoffier @pmlopes please review
> Resteasy examples

- Procfile
- heroku-example/README.md
> Fixed URL for Heroku button

- openshift3-examples/clustered-application/clustered-application-http/Dockerfile
- openshift3-examples/clustered-application/clustered-application-http/pom.xml
- openshift3-examples/clustered-application/clustered-application-service/Dockerfile
- openshift3-examples/clustered-application/clustered-application-service/pom.xml
- openshift3-examples/service-discovery-application/http-backend/Dockerfile
- openshift3-examples/service-discovery-application/http-backend/pom.xml
- openshift3-examples/service-discovery-application/http-frontend/Dockerfile
- openshift3-examples/service-discovery-application/http-frontend/pom.xml
- openshift3-examples/simple-web-application/Dockerfile
- openshift3-examples/simple-web-application/pom.xml
java:8-jre-alpine is deprecated
> Docker: use openjdk:8-jre-alpine

- docker-examples/vertx-docker-example/src/main/docker/Dockerfile
- docker-examples/vertx-docker-groovy/Dockerfile
- docker-examples/vertx-docker-java-fatjar/Dockerfile
- docker-examples/vertx-docker-java/Dockerfile
- docker-examples/vertx-docker-javascript/Dockerfile
- docker-examples/vertx-docker-ruby/Dockerfile
- openshift3-examples/clustered-application/clustered-application-http/Dockerfile
- openshift3-examples/clustered-application/clustered-application-service/Dockerfile
- openshift3-examples/service-discovery-application/http-backend/Dockerfile
- openshift3-examples/service-discovery-application/http-frontend/Dockerfile
- openshift3-examples/simple-web-application/Dockerfile
Follows up on vert-x3/vertx-stack#54
> Make the JVM get pid 1 to allow graceful shutdown

- mail-examples/README.adoc
turns out I cannot understand my own long sentences
> add a few dots, minor grammar changes.

- web-client-examples/src/main/java/io/vertx/example/webclient/oauth/TwitterOAuthExample.java
Using web client to call twitter's search tweets API.
This example shows how to use the web client for OAuth.
> Using web client to authenticate via OAuth for twitter

- web-examples/pom.xml
> Added slf4j-jul to vertx-web examples

- kafka-examples/README.adoc
Signed-off-by: Christoph Görn <goern@redhat.com>
> just this one typo

- kotlin-examples/web/build.gradle
- kotlin-examples/web/src/main/java/io/vertx/example/MainVerticle.kt
Moved commits to 3.5.0-staging as per #233
> Kotlin java8 examples

- maven-verticles/maven-verticle/README.adoc
> Minor revision of readme of simple example

- core-examples/src/main/java/io/vertx/example/core/net/greeter/Client.java
- core-examples/src/main/java/io/vertx/example/core/net/greeter/Server.java
- rxjava-2-examples/README.adoc
- rxjava-2-examples/src/main/java/io/vertx/example/reactivex/net/greeter/Client.java
- rxjava-2-examples/src/main/java/io/vertx/example/reactivex/net/greeter/Server.java
> Added an example on how to combine net client/server with RecordParser

- rxjava-2-examples/README.adoc
- rxjava-2-examples/pom.xml
- rxjava-2-examples/src/main/generated/io/vertx/example/reactivex/services/serviceproxy/SomeDatabaseServiceVertxEBProxy.java
- rxjava-2-examples/src/main/generated/io/vertx/example/reactivex/services/serviceproxy/SomeDatabaseServiceVertxProxyHandler.java
- rxjava-2-examples/src/main/generated/io/vertx/example/reactivex/services/serviceproxy/groovy/SomeDatabaseService_GroovyExtension.java
- rxjava-2-examples/src/main/generated/io/vertx/example/reactivex/services/serviceproxy/groovy/VertxExtensionModule.java
- rxjava-2-examples/src/main/generated/io/vertx/example/reactivex/services/serviceproxy/reactivex/SomeDatabaseService.java
- rxjava-2-examples/src/main/generated/vertx-rxified-serviceproxy-example-js/some_database_service.js
- rxjava-2-examples/src/main/generated/vertx-rxified-serviceproxy-example/some_database_service.rb
- rxjava-2-examples/src/main/java/io/vertx/example/reactivex/services/serviceproxy/ServiceConsumerVerticle.java
- rxjava-2-examples/src/main/java/io/vertx/example/reactivex/services/serviceproxy/SomeDatabaseService.java
- rxjava-2-examples/src/main/java/io/vertx/example/reactivex/services/serviceproxy/SomeDatabaseServiceVerticle.java
- rxjava-2-examples/src/main/java/io/vertx/example/reactivex/services/serviceproxy/impl/SomeDatabaseServiceImpl.java
- rxjava-2-examples/src/main/java/io/vertx/example/reactivex/services/serviceproxy/package-info.java
- rxjava-2-examples/src/main/java/io/vertx/example/util/Runner.java
The repo for now lacks an example for rx-ified service proxy with vertx-rx-java2, I think it would be nice if such an example is provided.
> Add an example for generate Rx-ified service proxy with vertx-rx-java2

- web-examples/README.adoc
- web-examples/src/main/java/io/vertx/example/web/openapi3/OpenAPI3Server.java
I've improved the openapi example for 3.5.1 release.
> Updated openapi example for 3.5.1 release

- junit5-examples/pom.xml
This fixes the problem stated in #276
> added junit-jupiter-engine in order to run junit5 tests in EclipseIDE

- infinispan-examples/README.adoc
- infinispan-examples/pom.xml
- infinispan-examples/src/main/java/io/vertx/example/infinispan/DisplayStatsApp.java
- infinispan-examples/src/main/java/io/vertx/example/infinispan/StatsConsumerApp.java
- infinispan-examples/src/main/java/io/vertx/example/infinispan/StatsProducerApp.java
- pom.xml
Clustered application example with Infinispan using a counter
> Infinispan cluster manager example

- web-examples/README.adoc
- web-examples/pom.xml
- web-examples/src/main/groovy/io/vertx/example/web/templating/rocker/server.groovy
- web-examples/src/main/groovy/io/vertx/example/web/templating/rocker/templates/index.rocker.html
- web-examples/src/main/groovy/io/vertx/example/web/templating/rocker/templates/main.rocker.html
- web-examples/src/main/java/io/vertx/example/web/templating/rocker/Server.java
- web-examples/src/main/java/io/vertx/example/web/templating/rocker/templates/index.rocker.html
- web-examples/src/main/java/io/vertx/example/web/templating/rocker/templates/main.rocker.html
- web-examples/src/main/js/io/vertx/example/web/templating/rocker/server.js
- web-examples/src/main/js/io/vertx/example/web/templating/rocker/templates/index.rocker.html
- web-examples/src/main/js/io/vertx/example/web/templating/rocker/templates/main.rocker.html
- web-examples/src/main/kotlin/io/vertx/example/web/templating/rocker/Server.kt
- web-examples/src/main/kotlin/io/vertx/example/web/templating/rocker/templates/index.rocker.html
- web-examples/src/main/kotlin/io/vertx/example/web/templating/rocker/templates/main.rocker.html
- web-examples/src/main/ruby/io/vertx/example/web/templating/rocker/server.rb
- web-examples/src/main/ruby/io/vertx/example/web/templating/rocker/templates/index.rocker.html
- web-examples/src/main/ruby/io/vertx/example/web/templating/rocker/templates/main.rocker.html
This took me way too long to setup in my project, so I'm adding an example here to make it faster for other people. :)
> Add Rocker templating example

- gradle-redeploy/build.gradle
Use file separator instead of OS value
> Update gradle-redeploy build.gradle

- docker-examples/README.adoc
- docker-examples/vertx-docker-ruby-gemfile/Dockerfile
- docker-examples/vertx-docker-ruby-gemfile/Gemfile
- docker-examples/vertx-docker-ruby-gemfile/config.json
- docker-examples/vertx-docker-ruby-gemfile/hello-dependency-verticle.rb
related to work done in: https://github.com/vert-x3/vertx-stack/issues/83
> Add ruby-gemfile docker example

- shell-examples/src/main/java/io/vertx/example/shell/prompt/PromptCommand.java
(cherry picked from commit 2b6757d)
> Add example on how to set the prompt

- mqtt-examples/src/main/groovy/io/vertx/example/mqtt/app/server.groovy
Fixes https://github.com/vert-x3/vertx-examples/issues/321
> MQTT server Groovy example fix

- README.adoc
Corrected a few basic grammatical mistakes which I found to be wrong.
> fix minor documentation mistakes

- README.adoc
- pom.xml
- web-graphql-example/README.adoc
- web-graphql-example/pom.xml
- web-graphql-example/src/main/java/io/vertx/example/web/graphql/Client.java
- web-graphql-example/src/main/java/io/vertx/example/web/graphql/Link.java
- web-graphql-example/src/main/java/io/vertx/example/web/graphql/Server.java
- web-graphql-example/src/main/java/io/vertx/example/web/graphql/User.java
- web-graphql-example/src/main/resources/links.graphqls
Closes https://github.com/vert-x3/vertx-web/issues/1218
> Vert.x Web GraphQL example code

- spring-examples/springboot-clustering/springboot-clustering-hazelcast/README.adoc
- spring-examples/springboot-clustering/springboot-clustering-hazelcast/pom.xml
- spring-examples/springboot-clustering/springboot-clustering-hazelcast/src/main/java/io/vertx/examples/spring/clustering/hazelcast/Application.java
- spring-examples/springboot-example/README.adoc
- spring-examples/springboot-example/pom.xml
1. Spring Boot version upgrade for module spring-examples/spring-example
2. Spring Boot version upgrade for module spring-examples/springboot-clustering/springboot-clustering-hazelcast
3. Updated the readme accordingly.
> Upgrading the spring boot version to 2.2.2.RELEASE

- spring-examples/spring-example/pom.xml
- spring-examples/spring-verticle-factory/pom.xml
- spring-examples/spring-worker-example/pom.xml
@tsegismont, Please take a look at this PR when you get a chance.
> spring framework version upgrade

- micrometer-metrics-examples/README.adoc
> fix packaging ometheus -> prometheus

- core-examples/src/main/java/io/vertx/example/core/future/ComposeExample.java
> fix the future deprecated

- spring-examples/springboot-example/src/main/java/io/vertx/example/Application.java
Motivation:
This is to solve the bug reported earlier: https://github.com/vert-x3/vertx-examples/issues/386
> changed from post construct to event listner
