vert-x3/vertx-examples

- gradle-verticle/README.adoc
While using gradle jars are kept inside build/libs rather target(like maven)
> Mistake in the fat Jar path

- unit-examples/src/test/java/io/vertx/example/unit/test/MyJUnitTest.java
AssertEquals was in the wrong callback. When the assert is false the async context already had finished.
> Fixing unit test example with junit

- core-examples/README.adoc
- core-examples/src/main/groovy/io/vertx/example/core/http/sharing/client.groovy
- core-examples/src/main/groovy/io/vertx/example/core/http/sharing/httpserververticle.groovy
- core-examples/src/main/java/io/vertx/example/core/http/sharing/Client.java
- core-examples/src/main/java/io/vertx/example/core/http/sharing/HttpServerVerticle.java
- core-examples/src/main/java/io/vertx/example/core/http/sharing/Server.java
- core-examples/src/main/js/io/vertx/example/core/http/sharing/client.js
- core-examples/src/main/js/io/vertx/example/core/http/sharing/httpserververticle.js
- core-examples/src/main/rb/io/vertx/example/core/http/sharing/client.rb
- core-examples/src/main/rb/io/vertx/example/core/http/sharing/httpserververticle.rb
This commit adds a section in the REDME file with some explanation and launch instructions
It also change how was made the example to allow code generation (codetrans)
It also modifies the example to rely on the `-instances`  vert.x parameter
It should answer to points opened by https://github.com/vert-x3/vertx-examples/pull/20#issuecomment-108827319
Signed-off-by: Clement Escoffier <clement.escoffier@gmail.com>
> Improve the sharing HTTP server example

- README.adoc
- osgi-examples/README.adoc
- osgi-examples/pom.xml
- osgi-examples/src/main/java/io/vertx/example/osgi/VertxActivator.java
- osgi-examples/src/main/java/io/vertx/example/osgi/VertxHttpClientVerticle.java
- osgi-examples/src/main/java/io/vertx/example/osgi/VertxHttpServer.java
- osgi-examples/src/main/java/io/vertx/example/osgi/VertxVerticleHost.java
- pom.xml
Add a few examples illustrating how Vert.x (core) can be used in an OSGi context.
This PR is related to https://github.com/eclipse/vert.x/pull/1058 and should only be merged once this one is merged.
> OSGi examples

- docker-examples/vertx-docker-example-fabric8/pom.xml
- docker-examples/vertx-docker-example/pom.xml
- docker-examples/vertx-docker-java-fatjar/pom.xml
- docker-examples/vertx-docker-java/pom.xml
- mail-examples/pom.xml
- maven-simplest/pom.xml
- maven-verticle/pom.xml
- openshift-example/pom.xml
- osgi-examples/pom.xml
I change pom.xml to refer to project.version instead of in some cases hardcoded value of 3.0.0-SNAPSHOT
It makes easier to switch to some version by "mvn versions:set" and get all i.e. using milestone6
> use_${project_version}_in_favor_or_hardcoded_3_0_0-SNAPSHOT

- gradle-simplest/build.gradle
Version 1.1.1 caused a StackOverflowError in my project:
Caused by: java.lang.StackOverflowError
at org.gradle.api.tasks.bundling.Jar.manifest(Jar.groovy:29)
at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar.super$8$manifest(ShadowJar.groovy)
at org.gradle.api.tasks.bundling.Jar.manifest(Jar.groovy:29)
at com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar.super$8$manifest(ShadowJar.groovy)
at org.gradle.api.tasks.bundling.Jar.manifest(Jar.groovy:29)
...
With version 1.2.2 this problem is gone.
> Upgrade shadow plugin to 1.2.2

- examples-utils/src/main/java/io/vertx/example/util/CodeTransProcessor.java
In order to avoid the generation of examples that does not actually work as expected, we need a way to configure codetrans to _skip_ the generation of these example.
This PR adds this features. It provide a way to configure codetrans using the `codetrans.config` argument pointing to a JSON file.
The JSON file is structured as follows:
```
{
"excludes": [
{
"package" : "the (java) package to exclude",
"langs" : ["lang1", "lang2"]
}
]
}
```
The `package` element is mandatory. It includes the specified packages and sub-packages. `Langs` is optional. When not set, all languages are skipped. Languages are identified by their _extensions_.
The "langs" option is useful as some examples are working as expected except in JavaScript.
> Add configuration support to codetrans

- spring-examples/springboot-example/pom.xml
- spring-examples/springboot-example/src/main/java/io/vertx/example/Application.java
- spring-examples/springboot-example/src/main/java/io/vertx/example/StaticServer.java
I'm up to date with my CLA.
This fixes the Spring Boot example so it actually uses Spring Boot (now you see the Spring Boot logo when you run it).
Because we are now actually using Spring Boot, we need to switch out the spring-boot-starter-web dependency, replacing it with just plain spring-boot-starter. Otherwise Spring Boot fires up embedded Tomcat, trying to listen on the same port as our Vert.x application.
I pulled the Vertx object out into a separate bean to make mocking easier (for people who base their apps on this model).
> Fix Spring Boot example so that we're actually using Spring Boot.

- Procfile
- app.json
- heroku-example/Procfile
- heroku-example/README.md
- heroku-example/pom.xml
In order for the Git deployment and Heroku button to work, the `Procfile` and `app.json` files need to be in the root directory of the project (this is a [12-factor thing](http://12factor.net/codebase) that doesn't really make sense here because this is just a grab bag of examples). They won't affect anything else I think, but I'm not sure if you want these in the root.
I've also added the config for the Heroku plugin, but it's using a version (0.5.6) that I'm releasing *right now*, so it may not work for an hour or two.
> Basic heroku support

- core-examples/src/main/java/io/vertx/example/core/eventbus/pubsub/Receiver.java
This makes it clear to new users that messages 'published' on eventBus will reach all consumers subscribed to that address.
> Add multiple eventbus consumers to the address

- gradle-redeploy/build.gradle
this fixes the '.' is not recognized as command issue in Windows
> use .\gradlew for Windows instead of ./gradlew

- osgi-examples/src/main/java/io/vertx/example/osgi/VertxWebApplication.java
I used a logger and found the route is called twice. I opened a bug on vertx-web.
its about 5 ms slower (on my machine with the logger) 9 ms instead of 4 ms
there are other places this can be fixed in this code sample.
> encodePrettily cause the code to be called twice

- spring-examples/pom.xml
- spring-examples/springboot-clustering/README.adoc
- spring-examples/springboot-clustering/pom.xml
- spring-examples/springboot-clustering/springboot-clustering-hazelcast/README.adoc
- spring-examples/springboot-clustering/springboot-clustering-hazelcast/pom.xml
- spring-examples/springboot-clustering/springboot-clustering-hazelcast/src/main/java/io/vertx/examples/spring/clustering/hazelcast/Application.java
- spring-examples/springboot-clustering/springboot-clustering-hazelcast/src/main/java/io/vertx/examples/spring/clustering/hazelcast/HelloVerticle.java
- spring-examples/springboot-clustering/springboot-clustering-hazelcast/src/main/java/io/vertx/examples/spring/clustering/hazelcast/HttpVerticle.java
- spring-examples/springboot-clustering/springboot-clustering-hazelcast/src/main/java/io/vertx/examples/spring/clustering/hazelcast/VertxProducer.java
- spring-examples/springboot-clustering/springboot-clustering-hazelcast/src/main/resources/hazelcast.xml
For now it's Hazelcast only but we can add Infinispan when the module is ready.
The goal is to provide a pointer for users having problems with Spring-managed clustering engines.
In particular, it shows:
* how you can setup/close Vert.x after/before Hazelcast
* how you should configure Hazelcast to disable its shutdown hook
> Adds a new Spring Boot clustering examples folder.

- spring-examples/README.adoc
- spring-examples/pom.xml
- spring-examples/spring-verticle-factory/README.adoc
- spring-examples/spring-verticle-factory/pom.xml
- spring-examples/spring-verticle-factory/src/main/java/io/vertx/examples/spring/verticlefactory/ExampleApplication.java
- spring-examples/spring-verticle-factory/src/main/java/io/vertx/examples/spring/verticlefactory/Greeter.java
- spring-examples/spring-verticle-factory/src/main/java/io/vertx/examples/spring/verticlefactory/GreetingVerticle.java
- spring-examples/spring-verticle-factory/src/main/java/io/vertx/examples/spring/verticlefactory/SpringVerticleFactory.java
It show how you can implement a VerticleFactory delegating bean initialization to the Spring Container.
This is  useful if you want to scale across cpus but still let Spring manage your verticles.
> Adds a new Spring Verticle Factory example

- maven-verticles/README.adoc
@cescoffier could you please review?
> trivial: remove redundant `is` from README

- spring-examples/README.adoc
- spring-examples/pom.xml
- spring-examples/spring-worker-example/README.adoc
- spring-examples/spring-worker-example/pom.xml
- spring-examples/spring-worker-example/src/main/asciidoc/dataobjects.adoc
- spring-examples/spring-worker-example/src/main/java/io/vertx/example/spring/worker/Application.java
- spring-examples/spring-worker-example/src/main/java/io/vertx/example/spring/worker/Book.java
- spring-examples/spring-worker-example/src/main/java/io/vertx/example/spring/worker/BookAsyncService.java
- spring-examples/spring-worker-example/src/main/java/io/vertx/example/spring/worker/BookAsyncServiceImpl.java
- spring-examples/spring-worker-example/src/main/java/io/vertx/example/spring/worker/BookRepository.java
- spring-examples/spring-worker-example/src/main/java/io/vertx/example/spring/worker/BookRestApi.java
- spring-examples/spring-worker-example/src/main/java/io/vertx/example/spring/worker/BookService.java
- spring-examples/spring-worker-example/src/main/java/io/vertx/example/spring/worker/SpringVerticleFactory.java
- spring-examples/spring-worker-example/src/main/java/io/vertx/example/spring/worker/SpringWorker.java
- spring-examples/spring-worker-example/src/main/java/io/vertx/example/spring/worker/package-info.java
- spring-examples/spring-worker-example/src/main/resources/application.properties
This example shows how you can embed Vert.x in SpringBoot, having:
- Spring container creating the verticles
- a standard verticle with Vert.x web for the REST API
- Spring backend services (with declarative transaction management and JPA repositories)
- a worker verticle exposing the Spring services over the event bus through service proxies
This might be useful if you have an existing Spring codebase and want to keep your data access layer.
> Spring worker example

- web-examples/src/main/java/io/vertx/example/web/vertxbus/java/Client.java
- web-examples/src/main/java/io/vertx/example/web/vertxbus/java/Server.java
* Add Vert.x event bus SockJS bridge example where the client is a Java
client using Vert.x HTTP client API to receive events over websockets.
As promised :)
> Add Java Vert.x event bus SockJS bridge example

- reactjs-server-side-rendering/package.json
- reactjs-server-side-rendering/webpack.config.js
`npm start` fails on this example, because of missing presets `es2015` and `react` in the webpack babel-loader config.
> Fix reactjs-server-side-rendering example

- grpc-examples/src/main/java/io/vertx/example/grpc/consumer/Client.java
- grpc-examples/src/main/java/io/vertx/example/grpc/consumer/Server.java
Current example throws an exception after the first two responses due to the value returned from `incrementAndGet` exceeding the enum value range for `PayloadType`. I've updated the example to set the payload type as `COMPRESSABLE` and the payload body as the int value from `incrementAndGet`. It also serves as a simple example of how to convert to and from a `ByteString`.
Hope it's useful.
> Use counter value as payload body

- kotlin-examples/kotlintest/readme.md
- kotlin-examples/kotlintest/testing-guide.md
There is some documentation missing in **kotlintest** project. For instance there is no readme file and testing guide. All missing documentation has been added to the project.
> Add documentation for kotlintest

- spring-examples/spring-worker-example/src/main/java/io/vertx/example/spring/worker/BookRestApi.java
- spring-examples/spring-worker-example/src/main/java/io/vertx/example/spring/worker/SpringWorker.java
First of all, thanks for providing an example of how you can use Vert.x worker in Spring.
Recently, I found deprecated message in IDE(Eclipse) vert.x 3.5.0 env,   "Vert.x ProxyHelper class is deprecated."
I've changed two parts in vertx-examples/spring-worker-example on using ServiceProxyBuilder and ServiceBinder class. 
This fixing source I changed based on the URL below.
[1]. http://vertx.io/docs/apidocs/index.html?io/vertx/serviceproxy/ProxyHelper.html
[2]. http://vertx.io/docs/vertx-service-proxy/java/
> Changing ProxyHelper class methods in vert.x3.5.0

- web-examples/src/main/java/io/vertx/example/web/cors/.editorconfig
- web-examples/src/main/java/io/vertx/example/web/cors/Server.java
- web-examples/src/main/java/io/vertx/example/web/cors/webroot/nopreflight.html
- web-examples/src/main/java/io/vertx/example/web/cors/webroot/preflight.html
Under the web-examples directory I noticed that the CORS nopreflight example was not working.  I fixed it changing the function that makes the asynchronous request following the style guide proposed at w3schools.com. I also have changed the preflight implementation to better display the response datas (they were displayed as a single line of text). I also changed the Server.java to better clarify how to correctly configure headers and HTTP methods in Vert.x
> fixed nopreflight.html, improved Server.java and preflight.html implementation

- README.adoc
The Link for the RxJava examples is broken.
Updates the RxJava example link to reflect the split into RxJava1 and RxJava2
> Fixes broken link to RxJava examples in Readme

- kotlin-examples/coroutines/src/main/kotlin/movierating/App.kt
Excerpt from the Kotlin docu on [GlobalScope and coroutines](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-global-scope/):
> Application code usually should use application-defined CoroutineScope, using async or launch on the instance of GlobalScope is highly discouraged.
Therefore, the extension function has been moved into the verticle, where the application-defined CoroutineScope is available.
> style: avoid using GlobalScope for coroutines.

- README.adoc
One link was broken, and some links pointed to folders rather than their READMEs for that example.
> Fix broken README links
